on:
  workflow_dispatch:

jobs:
  gpg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gpg
        env:
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
        run: |
          bash run.sh
