on:
  workflow_dispatch:

jobs:
  gpg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gpg
        env:
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
        run: |
          if [ -n "${{ secrets.DOES_NOT_EXIST }}"; then
            echo hi
          else
            echo bye
          fi

          gpg --version || echo failed
          age --version || echo failed
          sops --version || echo failed

          printf "%s" "${{ secrets.MULTILINE_SECRET }}" | wc -l
          echo "${{ secrets.MULTILINE_SECRET }}" | wc -l

          cosign -h

